// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table matches {
  id integer [primary key, increment]
  matchDate date [not null]
}

Table improvisations {
  id integer [primary key, increment]
  theme_id integer [not null]
  improvType integer [not null]
  minPlayers integer [not null]
  maxPlayers integer [not null]
  prepTime integer [not null]
  improvTime integer [not null]
  isFavorite boolean [not null]
}

Table improvTypes {
  id integer [primary key, increment]
  title text [not null]
  description text [not null]
  isFavorite boolean [not null]
}

Table themes {
  id integer [primary key, increment]
  title text [not null]
  isFavorite boolean [not null]
}

Table teams {
 id integer [primary key, increment]
 name text [not null]
 picture_url text [not null]
 notes text [not null]
}

Table scores {
  id integer [primary key, increment]
  match_id integer [not null]
  team_id integer [not null]
  score integer [not null]
  penalty_points integer [not null]
}

Table match_to_improv {
  id integer [primary key, increment]
  match_id integer [not null]
  improv_id integer [not null]
}

Ref: improvTypes.id < improvisations.improvType

Ref: themes.id < improvisations.theme_id

Ref: teams.id < scores.team_id

Ref: scores.match_id >  matches.id

Ref: matches.id < match_to_improv.match_id

Ref: improvisations.id < match_to_improv.improv_id