/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

/// Custom font to have custom icons into the Navigation bar
class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData whistleFull = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whistleEmpty = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
